config/routes.rb
Rails.application.routes.draw do
  resources :posts, :except => [:show] do
    resources :comments, :except => [:edit, :show, :update]
  end
  get '/posts/tag/:tag', to: "posts#index", as: :tag
  get '/posts/search/:search', to: "posts#index", as: :search
  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  has_many :comments
  acts_as_taggable_on :tags
end

app/models/tag_parser.rb
class TagParser < ActsAsTaggableOn::GenericParser
  def parse
    ActsAsTaggableOn::TagList.new.tap do |tag_list|
      tag_list.add @tag_list.split(' ')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all.order(:updated_on)
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      @comment.save
      format.html { redirect_to posts_path }
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    respond_to do |format|
      @comment.destroy
      format.html { redirect_to posts_path }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:title, :content, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_tags

ActsAsTaggableOn.default_parser = TagParser
ActsAsTaggableOn.remove_unused_tags = true

  def index
    if params[:search]
      @posts = Post.all.where("title LIKE :search OR content LIKE :search", search: "%#{params[:search].downcase}%").order(updated_on: :desc)
    elsif params[:tag]
      @posts = Post.tagged_with(params[:tag]).order(updated_on: :desc)
    else
      @posts = Post.all.order(updated_on: :desc)
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      @post.save
      format.html { redirect_to posts_path }
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      @post.update(post_params)
      format.html { redirect_to posts_path}
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @comment = @post.comments.where(post_id: @post.id)
    @comment.each do |comment|
      comment.destroy
    end
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path}
    end
  end

  def set_tags
    @all_tags = ActsAsTaggableOn::Tag.all.uniq
  end

  def search

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :tag_list)
    end
end

app/views/comments/_comment.html.erb
<% if comment.persisted? %>
<div id="<%= dom_id comment %>" class="comment-container">

  <div class="comment-title">
        <%=  comment.title %>
  </div>

  <%= link_to 'Delete', [comment.post, comment], class: 'comment-delete', data: { "turbo-method": :delete } %>

  <div class="comment-time">
    <%= comment.updated_on.strftime("%Y-%m-%d %H:%M:%S") %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>

</div>
<%  end %>

app/views/home/index.html.erb
<div class='home-container'>
  <h1>Welcome to open-blog</h1>
    <%= link_to 'Go to blog', posts_path , class:'confirm'%>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <%= link_to 'Home', posts_path, class:'button' %>
  <%= link_to 'Add post', new_post_path, class:'button' %>

  <%= form_tag(posts_path, :method => :get, class: "search") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
    <button type="submit" value="Search" class="submit" data-disable-with="Search">Search</button>
  <% end %>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <title>Open-blog</title>
    <meta charset="utf-8" name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class:"form-post-container") do |form| %>
    <div class='post-form'>
      <%= form.text_field :title, class: 'title', placeholder: "Title" %>
      <%= form.text_field :tag_list, placeholder: "Tags" %>
      <%= form.text_area :content, class: 'content-textarea', placeholder: "Content" %>
      <div class='manage-post'>
          <%= form.submit class:'send-post' %>
      </div>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class='post-container'>
  <div class='title'>
    <%= post.title %>
  </div>

  <div class= 'tags'>
    <% post.tag_list.each do |tag| %>
      <%= link_to "#" + tag, tag_path(tag: tag), class: "tag" %>
    <% end %>
  </div>

  <div class='time'>
    <%= post.updated_on.strftime("%Y-%m-%d %H:%M:%S") %>
  </div>
  <div class='content'>
    <%= post.content %>
  </div>
  <div class='manage-post'>
    <%= link_to "Edit this post", edit_post_path(post), class: 'edit-post' %>
    <%= link_to 'Delete', post, class: 'delete-post', data: { "turbo-method": :delete } %>
  </div>

  <div class="comments">
    <%= render post.comments %>
    <%= form_with(model: [post, post.comments.build], class:'comment-form-container') do |f| %>
      <div class="text">
        Add your comment!
      </div>
      <%= f.text_field :title, placeholder: "Title", class: "comment-input"%>
      <%= f.text_field :content, placeholder: "Content", class:"comment-input" %>
      <%= f.submit :class => "send-comment" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="chat-container">
  <%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<div class='home-post-container'>
  <div class="tags">
    <% @all_tags.each do |tag| %>
      <%= link_to "#"+ tag.name, tag_path(tag: tag.name), class: "tag" %>
    <% end %>
  </div>
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="chat-container">
  <%= render "form", post: @post %>
  <%= link_to "Back to posts", posts_path, class:'back-to-posts' %>
</div>